branch-defaults:
  master:
    environment: WhyCS-Prod-env
environment-defaults:
  WhyCS-Prod-env:
    branch: master
    repository: origin
global:
  application_name: WhyCS-Production
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Node.js running on
    64bit Amazon Linux/4.7.0
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
